package ar.gob.municipalidad.rentas;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.*;
import java.time.*;
import java.util.*;

@Service
class AdjustmentService {
    private final AdjustmentRepository adjustments;private final DebtRepository debts;private final PaymentPlanDebtRepository planDebts;private final PaymentPlanRepository plans;private final CurrentIdentity identity;private final AuditService audit;private final PaymentService events;
    AdjustmentService(AdjustmentRepository adjustments,DebtRepository debts,PaymentPlanDebtRepository planDebts,PaymentPlanRepository plans,CurrentIdentity identity,AuditService audit,PaymentService events){this.adjustments=adjustments;this.debts=debts;this.planDebts=planDebts;this.plans=plans;this.identity=identity;this.audit=audit;this.events=events;}
    @Transactional AdjustmentRequest create(ApiDtos.CreateAdjustmentRequest r){Debt debt=debt(r.debtId());CatalogService.require(debt.status!=DebtStatus.PAID&&debt.status!=DebtStatus.CANCELLED,"DEBT_NOT_ADJUSTABLE","La deuda no admite ajustes");CatalogService.require(!planDebts.existsByDebtIdAndStatus(debt.id,PaymentPlanDebtStatus.ACTIVE)&&!plans.existsByDebtIdAndStatus(debt.id,PaymentPlanStatus.ACTIVE),"DEBT_IN_ACTIVE_PAYMENT_PLAN","No se ajusta directamente una deuda incluida en un plan activo");AdjustmentRequest a=new AdjustmentRequest();a.debtId=debt.id;a.type=r.type();a.amount=PaymentService.money(r.amount());a.reason=r.reason();a.status=AdjustmentStatus.PENDING_APPROVAL;a.requestedBy=identity.get().userId();a.requestedAt=OffsetDateTime.now();adjustments.save(a);audit.record("AdjustmentRequest",a.id,"DEBT_ADJUSTMENT_REQUESTED",a);return a;}
    AdjustmentRequest get(Long id){return adjustments.findById(id).orElseThrow(()->CatalogService.notFound("Ajuste"));}
    @Transactional AdjustmentRequest approve(Long id,String observation){AdjustmentRequest a=get(id);CatalogService.require(a.status==AdjustmentStatus.PENDING_APPROVAL,"ADJUSTMENT_NOT_PENDING","El ajuste no está pendiente");Debt debt=debt(a.debtId);BigDecimal nextCurrent=switch(a.type){case DISCOUNT->debt.currentAmount.subtract(a.amount);case SURCHARGE,INTEREST->debt.currentAmount.add(a.amount);case CORRECTION->a.amount;};BigDecimal delta=nextCurrent.subtract(debt.currentAmount);BigDecimal nextOutstanding=debt.outstandingBalance.add(delta);BigDecimal paid=debt.currentAmount.subtract(debt.outstandingBalance);CatalogService.require(nextCurrent.compareTo(paid)>=0&&nextOutstanding.signum()>=0,"ADJUSTMENT_BELOW_PAID_AMOUNT","El ajuste reduciría la deuda por debajo de lo pagado");a.previousDebtAmount=debt.currentAmount;a.newDebtAmount=nextCurrent;a.status=AdjustmentStatus.APPROVED;a.resolvedBy=identity.get().userId();a.resolvedAt=OffsetDateTime.now();a.resolutionReason=observation;debt.currentAmount=nextCurrent;debt.outstandingBalance=nextOutstanding;debt.status=nextOutstanding.signum()==0?DebtStatus.PAID:(paid.signum()>0?DebtStatus.PARTIALLY_PAID:DebtStatus.PENDING);debt.updatedAt=OffsetDateTime.now();audit.record("AdjustmentRequest",a.id,"DEBT_ADJUSTED",a);events.addOutbox("debtAdjusted","Debt",debt.id,"{\"debtId\":"+debt.id+",\"adjustmentId\":"+a.id+"}");return a;}
    @Transactional AdjustmentRequest reject(Long id,String reason){AdjustmentRequest a=get(id);CatalogService.require(a.status==AdjustmentStatus.PENDING_APPROVAL,"ADJUSTMENT_NOT_PENDING","El ajuste no está pendiente");a.status=AdjustmentStatus.REJECTED;a.resolutionReason=reason;a.resolvedBy=identity.get().userId();a.resolvedAt=OffsetDateTime.now();audit.record("AdjustmentRequest",a.id,"DEBT_ADJUSTMENT_REJECTED",a);return a;}
    private Debt debt(Long id){return debts.findById(id).orElseThrow(()->CatalogService.notFound("Deuda"));}
}

@Service
class LiquidationRunService {
    private final LiquidationRunRepository runs;private final LiquidationRunItemRepository items;private final TaxConceptRepository concepts;private final TaxpayerRepository taxpayers;private final LiquidationService liquidations;private final CurrentIdentity identity;private final AuditService audit;
    LiquidationRunService(LiquidationRunRepository runs,LiquidationRunItemRepository items,TaxConceptRepository concepts,TaxpayerRepository taxpayers,LiquidationService liquidations,CurrentIdentity identity,AuditService audit){this.runs=runs;this.items=items;this.concepts=concepts;this.taxpayers=taxpayers;this.liquidations=liquidations;this.identity=identity;this.audit=audit;}
    @Transactional LiquidationRun create(ApiDtos.CreateLiquidationRunRequest r){concepts.findById(r.taxConceptId()).orElseThrow(()->CatalogService.notFound("Concepto"));CatalogService.require(!r.dueDate().isBefore(LocalDate.now()),"INVALID_DUE_DATE","El vencimiento no puede estar en el pasado");CatalogService.require(r.items().stream().map(ApiDtos.LiquidationRunItemRequest::taxpayerId).distinct().count()==r.items().size(),"DUPLICATE_RUN_TAXPAYER","La corrida repite un contribuyente");LiquidationRun run=new LiquidationRun();run.taxConceptId=r.taxConceptId();run.period=r.period();run.dueDate=r.dueDate();run.status=LiquidationRunStatus.DRAFT;run.totalItems=r.items().size();run.validItems=run.errorItems=0;run.estimatedTotalAmount=BigDecimal.ZERO.setScale(2);run.createdBy=identity.get().userId();run.createdAt=OffsetDateTime.now();runs.save(run);for(ApiDtos.LiquidationRunItemRequest input:r.items()){LiquidationRunItem item=new LiquidationRunItem();item.liquidationRunId=run.id;item.taxpayerId=input.taxpayerId();item.taxableBase=input.taxableBase();item.status=LiquidationRunItemStatus.PENDING;items.save(item);}return run;}
    ApiDtos.LiquidationRunDetail detail(Long id){LiquidationRun run=get(id);return new ApiDtos.LiquidationRunDetail(run,items.findByLiquidationRunIdOrderById(id));}
    @Transactional ApiDtos.LiquidationRunDetail preview(Long id){LiquidationRun run=get(id);CatalogService.require(run.status==LiquidationRunStatus.DRAFT,"RUN_NOT_DRAFT","Sólo se previsualiza una corrida borrador");run.validItems=run.errorItems=0;run.estimatedTotalAmount=BigDecimal.ZERO.setScale(2);for(LiquidationRunItem item:items.findByLiquidationRunIdOrderById(id)){item.previewAmount=null;item.errorCode=item.errorMessage=null;try{taxpayers.findById(item.taxpayerId).orElseThrow(()->CatalogService.notFound("Contribuyente"));ApiDtos.LiquidationPreview preview=liquidations.preview(request(run,item));if(run.configurationId==null){run.configurationId=preview.taxConfigurationId();run.configurationVersion=preview.configurationVersion();}CatalogService.require(run.configurationId.equals(preview.taxConfigurationId())&&run.configurationVersion==preview.configurationVersion(),"RUN_CONFIGURATION_CHANGED","La configuración cambió durante la previsualización");item.previewAmount=preview.finalAmount();item.status=LiquidationRunItemStatus.VALID;run.validItems++;run.estimatedTotalAmount=run.estimatedTotalAmount.add(preview.finalAmount());}catch(BusinessException ex){item.status=LiquidationRunItemStatus.ERROR;item.errorCode=ex.code;item.errorMessage=ex.getMessage();run.errorItems++;}}return detail(id);}
    @Transactional LiquidationRun submit(Long id){LiquidationRun run=get(id);CatalogService.require(run.status==LiquidationRunStatus.DRAFT&&run.validItems>0,"RUN_NOT_READY","La corrida debe previsualizarse y tener ítems válidos");run.status=LiquidationRunStatus.PENDING_APPROVAL;run.submittedAt=OffsetDateTime.now();return run;}
    @Transactional LiquidationRun approve(Long id,String observation){LiquidationRun run=get(id);CatalogService.require(run.status==LiquidationRunStatus.PENDING_APPROVAL,"RUN_NOT_PENDING","La corrida no está pendiente");run.status=LiquidationRunStatus.APPROVED;run.resolvedBy=identity.get().userId();run.resolvedAt=OffsetDateTime.now();audit.record("LiquidationRun",run.id,"LIQUIDATION_RUN_APPROVED",run);return run;}
    @Transactional LiquidationRun reject(Long id,String reason){LiquidationRun run=get(id);CatalogService.require(run.status==LiquidationRunStatus.PENDING_APPROVAL,"RUN_NOT_PENDING","La corrida no está pendiente");run.status=LiquidationRunStatus.REJECTED;run.resolvedBy=identity.get().userId();run.resolvedAt=OffsetDateTime.now();audit.record("LiquidationRun",run.id,"LIQUIDATION_RUN_REJECTED",run);return run;}
    @Transactional LiquidationRun execute(Long id){LiquidationRun run=get(id);CatalogService.require(run.status==LiquidationRunStatus.APPROVED,"RUN_NOT_APPROVED","La corrida debe estar aprobada");for(LiquidationRunItem item:items.findByLiquidationRunIdOrderById(id)){if(item.status!=LiquidationRunItemStatus.VALID)continue;Liquidation liquidation=liquidations.create(request(run,item));CatalogService.require(liquidation.taxConfigurationId.equals(run.configurationId)&&liquidation.configurationVersion==run.configurationVersion,"RUN_CONFIGURATION_CHANGED","La configuración cambió antes de ejecutar");item.liquidationId=liquidation.id;item.status=LiquidationRunItemStatus.LIQUIDATED;}run.status=LiquidationRunStatus.EXECUTED;audit.record("LiquidationRun",run.id,"LIQUIDATION_RUN_EXECUTED",run);return run;}
    private LiquidationRun get(Long id){return runs.findById(id).orElseThrow(()->CatalogService.notFound("Corrida de liquidación"));}
    private ApiDtos.LiquidationRequest request(LiquidationRun run,LiquidationRunItem item){return new ApiDtos.LiquidationRequest(item.taxpayerId,run.taxConceptId,run.period,item.taxableBase,run.dueDate);}
}
