package ar.gob.municipalidad.rentas;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.*;
import java.time.*;
import java.util.*;

@Service
class IndicatorService {
    private final PaymentRepository payments;private final DebtRepository debts;
    IndicatorService(PaymentRepository payments,DebtRepository debts){this.payments=payments;this.debts=debts;}
    ApiDtos.CollectionIndicatorResponse collection(LocalDate from,LocalDate to){List<Payment> selected=payments.findAll().stream().filter(x->x.status==PaymentStatus.CONFIRMED).filter(x->from==null||!x.paidAt.toLocalDate().isBefore(from)).filter(x->to==null||!x.paidAt.toLocalDate().isAfter(to)).toList();return new ApiDtos.CollectionIndicatorResponse(selected.size(),sumPayments(selected,x->x.amount),sumPayments(selected,x->x.allocatedAmount),sumPayments(selected,x->x.unallocatedAmount));}
    ApiDtos.DebtIndicatorResponse debt(){List<Debt> all=debts.findAll();return new ApiDtos.DebtIndicatorResponse(all.size(),all.stream().filter(x->x.status==DebtStatus.PAID).count(),all.stream().filter(this::open).count(),sumDebts(all,x->x.originalAmount),sumDebts(all,x->x.outstandingBalance));}
    ApiDtos.DelinquencyIndicatorResponse delinquency(){List<Debt> open=debts.findAll().stream().filter(this::open).toList();List<Debt> overdue=open.stream().filter(x->x.dueDate.isBefore(LocalDate.now())).toList();BigDecimal percentage=open.isEmpty()?BigDecimal.ZERO.setScale(2):BigDecimal.valueOf(overdue.size()).multiply(new BigDecimal("100")).divide(BigDecimal.valueOf(open.size()),2,RoundingMode.HALF_UP);return new ApiDtos.DelinquencyIndicatorResponse(overdue.size(),sumDebts(overdue,x->x.outstandingBalance),percentage);}
    ApiDtos.IndicatorSummaryResponse summary(LocalDate from,LocalDate to){return new ApiDtos.IndicatorSummaryResponse(collection(from,to),debt(),delinquency());}
    private boolean open(Debt x){return x.status!=DebtStatus.PAID&&x.status!=DebtStatus.CANCELLED&&x.outstandingBalance.signum()>0;}
    private BigDecimal sumPayments(List<Payment> values,java.util.function.Function<Payment,BigDecimal> field){return values.stream().map(field).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);}
    private BigDecimal sumDebts(List<Debt> values,java.util.function.Function<Debt,BigDecimal> field){return values.stream().map(field).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);}
}

@Service
class TaxpayerQueryService {
    private final TaxpayerRepository taxpayers;private final DebtRepository debts;private final PaymentRepository payments;private final PaymentPlanRepository plans;private final SocialBenefitRepository benefits;private final CurrentIdentity identity;
    TaxpayerQueryService(TaxpayerRepository taxpayers,DebtRepository debts,PaymentRepository payments,PaymentPlanRepository plans,SocialBenefitRepository benefits,CurrentIdentity identity){this.taxpayers=taxpayers;this.debts=debts;this.payments=payments;this.plans=plans;this.benefits=benefits;this.identity=identity;}
    ApiDtos.TaxpayerSummaryResponse summary(Long id){taxpayers.findById(id).orElseThrow(()->CatalogService.notFound("Contribuyente"));identity.requireOwnership(id);List<Debt> taxpayerDebts=debts.findByTaxpayerId(id);BigDecimal outstanding=taxpayerDebts.stream().map(x->x.outstandingBalance).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);BigDecimal paid=payments.findByTaxpayerId(id).stream().filter(x->x.status==PaymentStatus.CONFIRMED).map(x->x.amount).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);long open=taxpayerDebts.stream().filter(x->x.status!=DebtStatus.PAID&&x.status!=DebtStatus.CANCELLED).count();long activePlans=plans.findAll().stream().filter(x->x.taxpayerId.equals(id)&&x.status==PaymentPlanStatus.ACTIVE).count();long activeBenefits=benefits.findByTaxpayerId(id).stream().filter(x->x.calculatedStatus==SocialBenefitStatus.ACTIVE).count();return new ApiDtos.TaxpayerSummaryResponse(id,outstanding,paid,open,activePlans,activeBenefits);}
    ApiDtos.DebtSummaryResponse debtSummary(Long id){identity.requireOwnership(id);List<Debt> all=debts.findByTaxpayerId(id);long open=all.stream().filter(x->x.status!=DebtStatus.PAID&&x.status!=DebtStatus.CANCELLED).count();long paid=all.stream().filter(x->x.status==DebtStatus.PAID).count();long overdue=all.stream().filter(x->x.status!=DebtStatus.PAID&&x.status!=DebtStatus.CANCELLED&&x.dueDate.isBefore(LocalDate.now())).count();BigDecimal outstanding=all.stream().map(x->x.outstandingBalance).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);return new ApiDtos.DebtSummaryResponse(id,all.size(),open,paid,overdue,outstanding);}
}

@Service
class IntegrationReprocessService {
    private final IntegrationEventLogRepository logs;private final ObjectMapper json;private final ExternalObligationService obligations;private final TaxpayerIntegrationService taxpayers;private final TicketIntegrationService tickets;private final SocialBenefitIntegrationService benefits;private final ConfirmedM7Consumer m7;private final PreliminaryM4Consumer m4;
    IntegrationReprocessService(IntegrationEventLogRepository logs,ObjectMapper json,ExternalObligationService obligations,TaxpayerIntegrationService taxpayers,TicketIntegrationService tickets,SocialBenefitIntegrationService benefits,ConfirmedM7Consumer m7,PreliminaryM4Consumer m4){this.logs=logs;this.json=json;this.obligations=obligations;this.taxpayers=taxpayers;this.tickets=tickets;this.benefits=benefits;this.m7=m7;this.m4=m4;}
    IntegrationEventLog get(UUID eventId){return get(eventId.toString());}
    IntegrationEventLog get(String eventId){return logs.findFirstByExternalEventIdOrderByIdDesc(eventId).or(()->{try{return logs.findFirstByEventIdOrderByIdDesc(UUID.fromString(eventId));}catch(IllegalArgumentException ex){return Optional.empty();}}).orElseThrow(()->CatalogService.notFound("Evento de integración"));}
    @Transactional IntegrationEventLog reprocess(UUID eventId,String reason){return reprocess(eventId.toString(),reason);}
    @Transactional IntegrationEventLog reprocess(String eventId,String reason){IntegrationEventLog original=get(eventId);CatalogService.require(original.status==IntegrationEventStatus.FAILED||original.status==IntegrationEventStatus.DEAD_LETTER,"INTEGRATION_EVENT_NOT_REPROCESSABLE","El evento no está en error");original.retryCount++;original.lastRetryAt=OffsetDateTime.now();try{switch(original.eventType){case "permitFeeGenerated"->m4.consumePermitFee(readPermitFee(original));case "commercialFineGenerated"->m4.consumeCommercialFine(readCommercialFine(original));case "infractionConfirmed"->reprocessInfraction(original);case "taxpayerCreated","taxpayerUpdated","taxpayerSynchronized"->taxpayers.consume(json.readValue(original.payload,new TypeReference<ApiDtos.EventEnvelope<ApiDtos.TaxpayerEventData>>(){}));case "ticketCreated","ticketUpdated"->tickets.consume(json.readValue(original.payload,new TypeReference<ApiDtos.EventEnvelope<ApiDtos.TicketEventData>>(){}));case "socialBenefitUpdated"->benefits.consume(json.readValue(original.payload,new TypeReference<ApiDtos.EventEnvelope<ApiDtos.SocialBenefitEventData>>(){}));default->throw new BusinessException("UNSUPPORTED_EVENT_TYPE","No hay reprocesador para "+original.eventType,422);}return get(eventId);}catch(Exception ex){original.status=original.retryCount>=5?IntegrationEventStatus.DEAD_LETTER:IntegrationEventStatus.FAILED;original.errorMessage=(reason==null?"":reason+": ")+ex.getMessage();return original;}}
    private void reprocessInfraction(IntegrationEventLog original)throws Exception{if(json.readTree(original.payload).path("data").has("infractionId")){m7.consume(json.readValue(original.payload,ConfirmedInboundEvents.M7InfractionConfirmedEvent.class));return;}ApiDtos.EventEnvelope<ApiDtos.ExternalObligationData> e=readExternal(original);obligations.consumeInfraction(new ApiDtos.EventEnvelope<>(e.eventId(),e.eventType(),e.occurredAt(),e.sourceModule(),new ApiDtos.InfractionData(e.data().externalReferenceId(),e.data().taxpayerType(),e.data().taxpayerExternalId(),e.data().amount(),e.data().dueDate())));}
    private ApiDtos.EventEnvelope<ApiDtos.ExternalObligationData> readExternal(IntegrationEventLog log)throws Exception{return json.readValue(log.payload,new TypeReference<ApiDtos.EventEnvelope<ApiDtos.ExternalObligationData>>(){});}
    private PreliminaryM4Events.Envelope<PreliminaryM4Events.PermitFeeGeneratedData> readPermitFee(IntegrationEventLog log)throws Exception{return json.readValue(log.payload,new TypeReference<PreliminaryM4Events.Envelope<PreliminaryM4Events.PermitFeeGeneratedData>>(){});}
    private PreliminaryM4Events.Envelope<PreliminaryM4Events.CommercialFineGeneratedData> readCommercialFine(IntegrationEventLog log)throws Exception{return json.readValue(log.payload,new TypeReference<PreliminaryM4Events.Envelope<PreliminaryM4Events.CommercialFineGeneratedData>>(){});}
}
