ALTER TABLE liquidation ADD COLUMN discount_amount NUMERIC(19,2) NOT NULL DEFAULT 0;
ALTER TABLE liquidation ADD COLUMN surcharge_amount NUMERIC(19,2) NOT NULL DEFAULT 0;
ALTER TABLE liquidation ADD COLUMN interest_amount NUMERIC(19,2) NOT NULL DEFAULT 0;

CREATE TABLE liquidation_component (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liquidation_id BIGINT NOT NULL REFERENCES liquidation(id),
    type VARCHAR(32) NOT NULL CHECK (type IN ('BASE','DISCOUNT','EXEMPTION','SOCIAL_BENEFIT','SURCHARGE','INTEREST')),
    source_type VARCHAR(80) NOT NULL,
    source_id VARCHAR(120),
    description VARCHAR(255) NOT NULL,
    amount NUMERIC(19,2) NOT NULL CHECK (amount >= 0)
);

CREATE INDEX idx_liquidation_component_liquidation ON liquidation_component(liquidation_id);
